import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ask | 무엇이든 물어보세요.",
  description: "Generated by Hansebin",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="w-full h-screen">{children}</div>
      </body>
    </html>
  );
}
