import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Container from "./components/Container";

export const metadata: Metadata = {
  title: "Ask | 무엇이든 물어보세요.",
  description: "Generated by Hansebin",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="w-full h-screen">
          <Header />
          <section className="pt-section">
            <Container>{children}</Container>
          </section>
        </div>
      </body>
    </html>
  );
}
